### ISSUE TITLE
Add a more detailed description

### ISSUE THREAD

**Issue by juxeii** [knutkirkhorn/cisco-vpn-rdp-connecter#12]
A more detailed description on what problem this solves and how to use it, is much appreciated.
Thanky you :)

**Comment by knutkirkhorn** [comment]
Thanks for the suggestion! I've added a FAQ section in the readme that describes why this is made.
I'll also add a demo GIF in the readme later (see #11).
Is there anything else you feel is missing?

**Comment by juxeii** [comment]
Thanks. This is not what I expected. I would have thought that on machine A I can do RDP while on machine B I am connected to VPN via anyconnect. This is currently impossible, since anyconnect does not allow remote users.
Anyway, keep going ;)
